import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>       
        <div className="w-full min-h-screen bg-cover bg-center bg-no-repeat bg-[url('./asset/images/bg-light.jpg')] dark:bg-[url('./asset/images/bg-dark.jpg')]">
          <Navbar/>
          {children}
        </div>     
      </body>
    </html>
  );
}
